# Generated by Django 4.0.3 on 2022-04-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cart',
        ),
    ]
