# Generated by Django 4.0.3 on 2022-04-12 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_car_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '微信'), (2, '支付宝'), (3, '银联'), (4, '货到付款')], default=2, verbose_name='支付方式')),
                ('goods_num', models.IntegerField(verbose_name='商品数量')),
                ('goods_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('carriage_price', models.IntegerField(default=10, verbose_name='运费')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待付款'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态')),
                ('trade_on', models.CharField(max_length=128, verbose_name='支付编号')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.address', verbose_name='收货地址')),
                ('new_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('number', models.IntegerField(default=1, verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品单价')),
                ('comment', models.CharField(max_length=256, verbose_name='商品评价')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goods', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单商品表',
                'verbose_name_plural': '订单商品表',
                'db_table': 'order_goods',
            },
        ),
    ]
